# -*- coding: utf-8 -*-
"""bert_distilbert.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/162CcTZcsYD3tjMwYc8jag9FJXNg4SLUX
"""

!pip install -q datasets transformers evaluate scikit-learn matplotlib seaborn accelerate

import torch
import numpy as np
import pandas as pd
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModel, pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import gc

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Используемое устройство: {device}")

#Загрузка датасета
data = load_dataset("dair-ai/emotion", trust_remote_code=True)

train_texts = data['train']['text']
train_labels = data['train']['label']
val_texts = data['validation']['text']
val_labels = data['validation']['label']

results_table = []

def add_result(model_name, classifier_name, y_true, y_pred):
    acc = accuracy_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred, average='macro')
    results_table.append({
        "Модель": model_name,
        "Классификатор": classifier_name,
        "Accuracy": acc,
        "Macro-F1": f1
    })
    print(f"[{model_name} | {classifier_name}] Accuracy: {acc:.4f}, Macro-F1: {f1:.4f}")

def get_cls_embeddings(texts, model_name, batch_size=128):
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModel.from_pretrained(model_name).to(device)
    model.eval()

    all_embeddings = []

    for i in range(0, len(texts), batch_size):
        batch_texts = texts[i:i+batch_size]
        inputs = tokenizer(batch_texts, padding=True, truncation=True, return_tensors="pt").to(device)

        with torch.no_grad():
            outputs = model(**inputs)
            #Берем вектор первого токена [CLS]
            cls_emb = outputs.last_hidden_state[:, 0, :].cpu().numpy()
            all_embeddings.append(cls_emb)

    del model
    del tokenizer
    torch.cuda.empty_cache()
    gc.collect()

    return np.vstack(all_embeddings)

print("Feature Extraction без Fine-Tuning")

base_models = ["bert-base-uncased", "distilbert-base-uncased"]

for model_name in base_models:
    print(f"\nИзвлечение эмбеддингов для {model_name}...")
    X_train = get_cls_embeddings(train_texts, model_name)
    X_val = get_cls_embeddings(val_texts, model_name)

    #Logistic Regression
    clf_lr = LogisticRegression(max_iter=1000)
    clf_lr.fit(X_train, train_labels)
    preds_lr = clf_lr.predict(X_val)
    add_result(model_name, "Logistic Regression", val_labels, preds_lr)

    #SVM (LinearSVC для скорости)
    clf_svm = LinearSVC(max_iter=2000, dual=False)
    clf_svm.fit(X_train, train_labels)
    preds_svm = clf_svm.predict(X_val)
    add_result(model_name, "SVM (Linear)", val_labels, preds_svm)

print("\nГотовые Fine-Tuned модели")

finetuned_models = [
    "bhadresh-savani/bert-base-uncased-emotion",
    "Panda0116/emotion-classification-model" # DistilBERT
]

for model_name in finetuned_models:
    print(f"\nРабота с {model_name}")

    classifier = pipeline("text-classification", model=model_name, device=0, truncation=True, max_length=512)

    model_label2id = {k.lower(): v for k, v in classifier.model.config.label2id.items()}

    for i in range(6):
        model_label2id[f"label_{i}"] = i

    print("Получение предсказаний встроенного классификатора")
    pipe_preds = classifier(list(val_texts), batch_size=128)

    preds_pipe = [model_label2id[p['label'].lower()] for p in pipe_preds]
    add_result(model_name, "Встроенный (Pipeline)", val_labels, preds_pipe)

    del classifier
    torch.cuda.empty_cache()

    print("Извлечение CLS эмбеддингов из fine-tuned модели")
    X_train = get_cls_embeddings(train_texts, model_name)
    X_val = get_cls_embeddings(val_texts, model_name)

    clf_svm = LinearSVC(max_iter=2000, dual=False)
    clf_svm.fit(X_train, train_labels)
    preds_svm = clf_svm.predict(X_val)
    add_result(f"{model_name} (CLS)", "SVM (Linear)", val_labels, preds_svm)

print("\nСобственный Fine-Tuning")
from transformers import AutoModelForSequenceClassification, TrainingArguments, Trainer

ft_model_name = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(ft_model_name)

def tokenize_function(examples):
    return tokenizer(examples["text"], padding="max_length", truncation=True)

tokenized_datasets = data.map(tokenize_function, batched=True)

model_ft = AutoModelForSequenceClassification.from_pretrained(ft_model_name, num_labels=6).to(device)

training_args = TrainingArguments(
    output_dir="./emotion_results",
    learning_rate=2e-5,
    per_device_train_batch_size=32,
    per_device_eval_batch_size=32,
    num_train_epochs=3, #3 эпохи
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    fp16=True, #Mixed Precision для ускорения на GPU
    seed=42,
    logging_steps=100
)

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return {
        "accuracy": accuracy_score(labels, predictions),
        "macro_f1": f1_score(labels, predictions, average="macro")
    }

trainer = Trainer(
    model=model_ft,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
    compute_metrics=compute_metrics,
)

trainer.train()

print("Оценка после Fine-Tuning")
eval_results = trainer.evaluate()
add_result("Мой Fine-Tuned BERT", "Встроенный", val_labels, np.argmax(trainer.predict(tokenized_datasets["validation"]).predictions, axis=-1))

trainer.save_model("./my_best_emotion_model")
tokenizer.save_pretrained("./my_best_emotion_model")

del model_ft, trainer
torch.cuda.empty_cache()
gc.collect()

print("Извлечение CLS из нашей дообученной модели")
X_train_my = get_cls_embeddings(train_texts, "./my_best_emotion_model")
X_val_my = get_cls_embeddings(val_texts, "./my_best_emotion_model")

clf_svm_my = LinearSVC(max_iter=2000, dual=False)
clf_svm_my.fit(X_train_my, train_labels)
preds_svm_my = clf_svm_my.predict(X_val_my)
add_result("Мой Fine-Tuned BERT (CLS)", "SVM (Linear)", val_labels, preds_svm_my)

print("\nИтоговая таблица")

df_results = pd.DataFrame(results_table)
display(df_results.sort_values(by="Accuracy", ascending=False).reset_index(drop=True))